### ISSUE TITLE
Issue with installation instructions

### ISSUE THREAD

**Issue by SamWright822** [ChakradharG/PeptideBERT#1]
hi! 

I tried to follow the installation instructions on your readme, but it looks like there may be a disconnect between these two steps:

> - Download the datasets by running python data/download_data.py
> - Run python data/split_augment.py to convert the data into the required format

as I am able to complete the first step, but here is the structure at that point:
  | - data
  |  | - nf-negative.npz
  |  | - sol-negative.npz
  |  | - analysis.py
  |  | - sol-positive.npz
  |  | - split_augment.py
  |  | - __pycache__
  |  |  | - convert_encodings.cpython-311.pyc
  |  | - nf-positive.npz
  |  | - hemo-positive.npz
  |  | - dataset.py
  |  | - download_data.py
  |  | - dataloader.py
  |  | - convert_encodings.py
  |  | - hemo-negative.npz
  
  and here is the error message I get when I run the python command:
  
  ```
Traceback (most recent call last):
  File "/Users/samanthacox/Documents/research/pepbert/PeptideBERT/data/split_augment.py", line 215, in <module>
    main()
  File "/Users/samanthacox/Documents/research/pepbert/PeptideBERT/data/split_augment.py", line 209, in main
    split_data('hemo')
  File "/Users/samanthacox/Documents/research/pepbert/PeptideBERT/data/split_augment.py", line 30, in split_data
    np.savez(
  File "/opt/anaconda3/envs/pepbert/lib/python3.11/site-packages/numpy/lib/npyio.py", line 639, in savez
    _savez(file, args, kwds, False)
  File "/opt/anaconda3/envs/pepbert/lib/python3.11/site-packages/numpy/lib/npyio.py", line 736, in _savez
    zipf = zipfile_factory(file, mode="w", compression=compression)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pepbert/lib/python3.11/site-packages/numpy/lib/npyio.py", line 103, in zipfile_factory
    return zipfile.ZipFile(file, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/pepbert/lib/python3.11/zipfile.py", line 1284, in __init__
    self.fp = io.open(file, filemode)
              ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data/hemo/train.npz'
  ```
  
 I think this may be a simple fix, it just looks like files don't exist? Maybe I did something incorrectly, not sure. Thanks!

**Comment by ChakradharG** [comment]
Thank you for highlighting this issue. The problem stemmed from the missing (in this case `hemo/`) sub-directory within the `data/` directory. This has now been fixed. Kindly pull the latest commit, and everything should function as expected.
