### ISSUE TITLE
network problem associated with the main.py?

### ISSUE THREAD

**Issue by BinhongLiu** [ChakradharG/PeptideBERT#5]
Hi, I encountered some issues when perform the `main.py` script. Could you help me with this, please?
`python main.py`

output:

Device: cpu

==============================        DATA        ==============================
Batch size:  32
Train dataset samples:  14946
Validation dataset samples:  1661
Test dataset samples:  1846
Train dataset batches:  468
Validation dataset batches:  52
Test dataset batches:  58

Traceback (most recent call last):
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/connection.py", line 213, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x2afcf739aa10>: Failed to establish a new connection: [Errno 101] Network is unreachable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Rostlab/prot_bert_bfd/resolve/main/tf_model.h5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2afcf739aa10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/home/ac1daawz21/software/PeptideBERT/main.py", line 56, in <module>
    model = create_model(config)
            ^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/software/PeptideBERT/model/network.py", line 35, in create_model
    model = PeptideBERT(bert_config).to(config['device'])
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/software/PeptideBERT/model/network.py", line 11, in __init__
    self.protbert = BertModel.from_pretrained(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2559, in from_pretrained
    if has_file(pretrained_model_name_or_path, TF2_WEIGHTS_NAME, **has_file_kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/transformers/utils/hub.py", line 610, in has_file
    r = requests.head(url, headers=headers, allow_redirects=False, proxies=proxies, timeout=10)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/requests/api.py", line 100, in head
    return request("head", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/home/ac1daawz21/miniconda3/envs/PeptideBERT/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url: /Rostlab/prot_bert_bfd/resolve/main/tf_model.h5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x2afcf739aa10>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

**Comment by ChakradharG** [comment]
The error seems to arise when `transformers` is trying to download the pre-trained model from HuggingFace. I know HuggingFace was down for a while recently, so that might be the root cause of the error. Can you try running the code again? because I am not able to reproduce this on my machine.

**Comment by BinhongLiu** [comment]
Thanks for your prompt reply.
I tried but the error was still there. Yes, this may caused by the firewalled environment of my server. I found the pre-trained model here [https://huggingface.co/Rostlab/prot_bert_bfd/tree/main](url). Could I download the pre-trained model and other files manually and place them into the `model` folder directly to run the code offline? 
I want to analyze the properties of several thousands of peptides using the pre-trained model. Would you provide a more detailed `[tutorial.ipynb](https://github.com/ChakradharG/PeptideBERT/blob/master/tutorial.ipynb)`  for this, please? Thanks!

**Comment by ChakradharG** [comment]
I believe you can download the model and run it that way. I'll add how to do that as well as the steps for using the model with custom sequences to the `tutorial.ipynb` file.

**Comment by ChakradharG** [comment]
I have improved `tutorial.ipynb` to make it more comprehensive (Now includes walk-through for training on custom datasets and inference using trained model).
